name: Next.js CI/CD Workflow

on:
  push:
    branches: ['*']  # Run on pushes to any branch
  pull_request:
    branches: [main]  # Run on pull requests merging to main
    types: [closed]  # Only run when PR is merged

jobs:
   build-and-test:
     runs-on: ubuntu-latest  # Use a suitable runner

     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
         with:
           node-version: 20  # Adjust if needed
       - run: npm ci
       - run: npm run build
       - run: npm run test

   build-test-and-integ-test:
     runs-on: ubuntu-latest

     needs: build-and-test  # Ensure build-and-test job runs first

     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
         with:
           node-version: 20
       - run: npm ci
       - run: npm run build
       - run: npm run test
       - run: npm run integ-test